"use strict ";
const axios = require("axios") ;
const apikey = c70baf0d17017c73b02836e1a8839975 ; // your api key to the api generated by the website

const getWeather = location => {
    return new Promise(async(resolve, reject) => {
        try {
            const weatherConditions = await axios.get(`https://api.openweathermap.org/data/2.5/weather?q=${q}&appid=${key}`,
            {
                params : {
                    key: apikey,
                    q: location,
            }
        });

        resolve (weatherConditions.data) // returns back the results to the chatbot

    }
    catch (error) {
        reject (error);
    }
  }); 
}

module.exports = getWeather ;
